.\" xfce4-screensaver manual page
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.TH XFCE-SCREENSAVER 1 "14 October 2018" "Xfce Desktop Environment"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH "NAME"
xfce4-screensaver \- The Xfce Desktop Screensaver and Locker
.SH "SYNOPSIS"
.B xfce4-screensaver [OPTIONS]
.SH "DESCRIPTION"
Xfce Screensaver is the default screen saver and locker for the Xfce Desktop. It is designed with simplicity and security in mind. \fBxfce4-screensaver\fP integrates well with the Xfce desktop, and it supports User Switching and the ability to lock down configuration settings.
.SH "OPTIONS"
.TP
\fB\-\-display=DISPLAY\fR
X display to use.
.TP
.TP
\fB\-\-debug\fR
Enable debugging messages for \fBxfce4-screensaver\fP
.TP
\fB\-\-version\fR
Output version information and exit.
.TP
\fB\-h, \-\-help\fR
Print standard command line options.
.TP
\fB\-\-help\-all\fR
Print all command line options.
.P
This program also accepts the standard GTK options.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
https://bugzilla.xfce.org
.SH "AUTHORS"
.SS xfce4-screensaver is maintained by:
.nf
Sean Davis <bluesabre@xfce.org>
Simon Steinbeiss <ochosi@xfce.org>
.fi
.SS This Man Page has been updated for the Xfce Desktop Environment by:
Sean Davis <bluesabre@xfce.org> (2018)
.SH "HISTORY"
.SS gnome-screensaver was written by William Jon McCann <mccann@jhu.edu>
.SS This manual page was originally written by Sven Arvidsson <sa@whiz.se> (2007)
.SH "SEE ALSO"
.SS Further information may also be available at: https://docs.xfce.org/
.P
.BR xfce4-screensaver-command (1),
.BR xfce4-screensaver-preferences (1),
.BR gtk-options (7)
